/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AlbumCard: typeof import('./src/components/AlbumCard/AlbumCard.vue')['default']
    Button: typeof import('./src/components/Button/Button.vue')['default']
    Card: typeof import('./src/components/PlayListCard/Card.vue')['default']
    CodeLogin: typeof import('./src/components/CodeLogin/CodeLogin.vue')['default']
    ImgLoad: typeof import('./src/components/ImgLoad/ImgLoad.vue')['default']
    Input: typeof import('./src/components/Input/Input.vue')['default']
    Message: typeof import('./src/components/Message/Message.vue')['default']
    MessageBox: typeof import('./src/components/MessageBox/MessageBox.vue')['default']
    MInput: typeof import('./src/components/Input/MInput.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NEmpty: typeof import('naive-ui')['NEmpty']
    NH1: typeof import('naive-ui')['NH1']
    NH2: typeof import('naive-ui')['NH2']
    NH3: typeof import('naive-ui')['NH3']
    NIcon: typeof import('naive-ui')['NIcon']
    NImage: typeof import('naive-ui')['NImage']
    NInput: typeof import('naive-ui')['NInput']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutFooter: typeof import('naive-ui')['NLayoutFooter']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NPagination: typeof import('naive-ui')['NPagination']
    NResult: typeof import('naive-ui')['NResult']
    NSpace: typeof import('naive-ui')['NSpace']
    NSpin: typeof import('naive-ui')['NSpin']
    NTab: typeof import('naive-ui')['NTab']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    NTag: typeof import('naive-ui')['NTag']
    PlaylistCard: typeof import('./src/components/Card/PlaylistCard.vue')['default']
    PlayListCard: typeof import('./src/components/PlayListCard/PlayListCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TabBar: typeof import('./src/components/TabBar/TabBar.vue')['default']
    ThemeBtn: typeof import('./src/components/ThemeBtnExp/ThemeBtn.vue')['default']
    ThemeBtnEx: typeof import('./src/components/ThemeBtnExp/ThemeBtnEx.vue')['default']
    ThemeBtnExp: typeof import('./src/components/ThemeBtnExp/ThemeBtnExp.vue')['default']
    UserInfor: typeof import('./src/components/UserInfor/UserInfor.vue')['default']
    UserItem: typeof import('./src/components/UserInfor/components/UserItem/UserItem.vue')['default']
    UserPlaylist: typeof import('./src/components/UserPlaylist/UserPlaylist.vue')['default']
    UserPlayList: typeof import('./src/components/UserPlayList/UserPlayList.vue')['default']
  }
}
